#include <stdio.h>
#include <string.h>

char* cousaboa(char* jsonstring, const char* key) {
    char* start = strstr(jsonstring, key);
    return start;
}

int main(int argc, char const *argv[])
{
    char* strings = "fkjsahjfkanjfasjdnfnsafsndkjfnkey:sjfkhfukahhfkjhfjkahsjflhjahlkdgjdhagkhluifyigukHFULGKFHLUSGKJFVKNWECGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHGNIOVBYGUNWOCYNHOMUCYIGAUKHIUFGHJLSFKHZSJLSGHO8YTHUIREYOGHULIORYZFHULOIEWRYOHUREOWPOYRHUEPW8TYGFHUIYOIGIUOPYGHLUYOZSHUUOIfanfkjdahfauhiaehfwannsdfhsfasfhaijsfjkdfka";
    const char* key = "key:";
    
    char* start = cousaboa(strings, key);

    printf("print do coiso\n%s", start);
    getchar();
    return 0;
}
